[features]
seeds = false
skip-lint = false
[programs.devnet]
crowdfunding_dapp = "DqGfiavJezxHcTPzDcvfhKraq4p9EfvEc6WgwycpnkWd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/anoy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
